import { Footer } from '@/components/layout/footer'
import { Header } from '@/components/layout/header'

export const metadata = {
  title: 'ADAS | Associação dos Direitos dos Animais de Saquarema',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt">
      <body>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  )
}
